### ISSUE TITLE
append to debugtoolbar.extra_panels instead of debugtoolbar.panels

### ISSUE THREAD

**Issue by mmerickel** [jvanasco/pyramid_debugtoolbar_ajax#1]
If you fix this it will be forward compatible with debugtoolbar 4.0. Same with the dogpile addon.

**Comment by jvanasco** [comment]
thanks. both are on my todo list.

i've got time scheduled to maintain 2 packages that depend on the next `requests` release, which should come within the next week or to.  all my debugtoolbar fixes will get handled that morning.

**Comment by jvanasco** [comment]
fixed in `v0.1.0` on PyPi and Github
